#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
   CREATE USER $POSTGRES_USER password '$POSTGRES_PASSWORD' superuser;
   CREATE DATABASE $POSTGRES_DB OWNER $POSTGRES_USER LC_COLLATE='en_US.utf8' LC_CTYPE='en_US.utf8' TEMPLATE template0;
EOSQL
